# Generated by Django 6.1 on 2026-08-16 10:08

import django.core.validators
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_application_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), jobs.models.validate_resume_size]),
        ),
    ]
